version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=yessstyle
      - DB_USER=yessuser
      - DB_PASS=yesspass
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html:z

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=yessstyle
      - MYSQL_USER=yessuser
      - MYSQL_PASSWORD=yesspass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:

